server:
  port: 10000
easyEye:
  main:
    host: 127.0.0.1
    port: 8083
  auto-register: true
  name: "zdf"
spring:
  datasource:
    url: "jdbc:h2:~/client;DATABASE_TO_UPPER=false;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;"
  h2:
    console:
      enabled: true